//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apmservice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class astockEntities : DbContext
    {
        public astockEntities()
            : base("name=astockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STK_MKT_ConsolidatedReturn> STK_MKT_ConsolidatedReturn { get; set; }
        public virtual DbSet<STK_MKT_DeriativeTradingIndexDaily> STK_MKT_DeriativeTradingIndexDaily { get; set; }
        public virtual DbSet<STK_MKT_IndexDaily> STK_MKT_IndexDaily { get; set; }
        public virtual DbSet<STK_MKT_PortfolioBase> STK_MKT_PortfolioBase { get; set; }
        public virtual DbSet<STK_MKT_RiskFactorDaily> STK_MKT_RiskFactorDaily { get; set; }
        public virtual DbSet<STK_MKT_TradeDaily> STK_MKT_TradeDaily { get; set; }
        public virtual DbSet<TRD_Co> TRD_Co { get; set; }
        public virtual DbSet<TRD_Co_Quarter_ProfitIndex> TRD_Co_Quarter_ProfitIndex { get; set; }
        public virtual DbSet<TRD_Sector> TRD_Sector { get; set; }
        public virtual DbSet<STK_MKT_SectorDaily> STK_MKT_SectorDaily { get; set; }
    }
}
