//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apmservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_MKT_TradeDaily
    {
        public string StockID { get; set; }
        public string TradeDate { get; set; }
        public Nullable<double> OpenPrice { get; set; }
        public Nullable<double> HighPrice { get; set; }
        public Nullable<double> LowPrice { get; set; }
        public Nullable<double> ClosePrice { get; set; }
        public Nullable<double> SumStockTrade { get; set; }
        public Nullable<double> SumVolumeTrade { get; set; }
        public Nullable<double> SumCirculatedMarketValue { get; set; }
        public Nullable<double> SumTotalMarketValue { get; set; }
        public Nullable<double> ReturnRateReinvest { get; set; }
        public Nullable<double> ReturnRateNonReinvest { get; set; }
        public Nullable<double> ClosePriceComparableReinvest { get; set; }
        public Nullable<double> ClosePriceComparableNonReinvest { get; set; }
        public Nullable<double> MarketType { get; set; }
        public string LatestCapitalChangeDate { get; set; }
        public Nullable<double> TradeStatus { get; set; }
        public System.Guid UniqueID { get; set; }
        public Nullable<System.DateTime> TradeDate2 { get; set; }
    
        public virtual TRD_Co TRD_Co { get; set; }
    }
}
