//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apmservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_MKT_DeriativeTradingIndexDaily
    {
        public System.Guid UniqueID { get; set; }
        public double SecurityID { get; set; }
        public string TradingDate { get; set; }
        public string Symbol { get; set; }
        public string ShortName { get; set; }
        public Nullable<double> Ret { get; set; }
        public Nullable<double> PE { get; set; }
        public Nullable<double> PB { get; set; }
        public Nullable<double> PCF { get; set; }
        public Nullable<double> PS { get; set; }
        public Nullable<double> Turnover { get; set; }
        public Nullable<double> CirculatedMarketValue { get; set; }
        public Nullable<double> ChangeRatio { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Liquidility { get; set; }
        public Nullable<System.DateTime> TradingDate2 { get; set; }
    
        public virtual TRD_Co TRD_Co { get; set; }
    }
}
