//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apmservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_MKT_ConsolidatedReturn
    {
        public Nullable<double> MarketType { get; set; }
        public string TradeDate { get; set; }
        public Nullable<double> SharesExchangedAmount { get; set; }
        public Nullable<double> TransactionValueAmount { get; set; }
        public Nullable<double> AverageWeightReturnRateReinvest { get; set; }
        public Nullable<double> AverageWeightReturnRateNonReinvest { get; set; }
        public Nullable<double> CirculatedMarketCapitalWeightedReturnRateReinvest { get; set; }
        public Nullable<double> CirculatedMarketCapitalWeightedReturnRateNonReinvest { get; set; }
        public Nullable<double> TotalMarketCapitalWeightedReturnRateReinvest { get; set; }
        public Nullable<double> TotalMarketCapitalWeightedReturnRateNonReinvest { get; set; }
        public Nullable<double> NumOfCompaniesInCal { get; set; }
        public System.Guid UniqueID { get; set; }
        public Nullable<System.DateTime> TradeDate2 { get; set; }
    }
}
