//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apmservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRD_Co_Quarter_ProfitIndex
    {
        public string StockID { get; set; }
        public string DateAsOfReporting { get; set; }
        public string TypeOfReport { get; set; }
        public string IndustryID { get; set; }
        public Nullable<double> ReturnOnAssetA { get; set; }
        public Nullable<double> ReturnOnAssetB { get; set; }
        public Nullable<double> ReturnOnAssetC { get; set; }
        public Nullable<double> ReturnOnAssetTTM { get; set; }
        public Nullable<double> ReturnOnTotalAssetA { get; set; }
        public Nullable<double> ReturnOnTotalAssetB { get; set; }
        public Nullable<double> ReturnOnTotalAssetC { get; set; }
        public Nullable<double> ReturnOnTotalAssetTTM { get; set; }
        public string ReturnOnLiquidityA { get; set; }
        public string ReturnOnLiquidityB { get; set; }
        public string ReturnOnLiquidityC { get; set; }
        public string ReturnOnLiquidityTTM { get; set; }
        public Nullable<double> ReturnOnFixedAssetValueA { get; set; }
        public Nullable<double> ReturnOnFixedAssetValueB { get; set; }
        public Nullable<double> ReturnOnFixedAssetValueC { get; set; }
        public Nullable<double> ReturnOnFixedAssetValueTTM { get; set; }
        public Nullable<double> ReturnOnNetAssetValueA { get; set; }
        public Nullable<double> C_ReturnOnNetAssetValueB { get; set; }
        public Nullable<double> C_ReturnOnNetAssetValueC { get; set; }
        public Nullable<double> C_ReturnOnNetAssetValueTTM { get; set; }
        public Nullable<double> EBIT { get; set; }
        public Nullable<double> EBITTTM { get; set; }
        public Nullable<double> NOPLAT { get; set; }
        public Nullable<double> EBITDA { get; set; }
        public Nullable<double> EBITDATTM { get; set; }
        public Nullable<double> RatioNetToGrossProfit { get; set; }
        public Nullable<double> RatioTotalProfitToEBITDA { get; set; }
        public Nullable<double> RatioEBITDAToTotalAsset { get; set; }
        public Nullable<double> ReturnOnCapitalEmployed { get; set; }
        public Nullable<double> LongTermROE { get; set; }
        public string GrossMargin { get; set; }
        public string GrossMarginTTM { get; set; }
        public string OperatingCostRate { get; set; }
        public string OperatingCostRateTTM { get; set; }
        public string OperatingProfitRate { get; set; }
        public string OperatingProfitRateTTM { get; set; }
        public string OperatingMargin { get; set; }
        public string OperatingMarginTTM { get; set; }
        public Nullable<double> TotalOperatingCostRate { get; set; }
        public Nullable<double> TotalOperatingCostRateTMM { get; set; }
        public string MarketingExpenseRate { get; set; }
        public string MarketingExpenseRateTTM { get; set; }
        public string MgmtExpenseRate { get; set; }
        public string MgmtExpenseRateTTM { get; set; }
        public string FinanceExpenseRate { get; set; }
        public string FinanceExpenseRateTTM { get; set; }
        public string SalesExpenseRate { get; set; }
        public string SalesExpenseRateTTM { get; set; }
        public string ProfitToCostNExpense { get; set; }
        public string ProfitToCostNExpenseTTM { get; set; }
        public string AssetInpairmentLoss { get; set; }
        public string AssetInpairmentLossTTM { get; set; }
        public Nullable<double> EBITDAProfitRate { get; set; }
        public Nullable<double> EBITDAProfitRateTTM { get; set; }
        public string EBITProfitRate { get; set; }
        public string EBITProfitRateTTM { get; set; }
        public Nullable<double> TotalCashFlowToProfit { get; set; }
        public Nullable<double> TotalCashFlowToProfitTTM { get; set; }
        public Nullable<double> ReturnOnNetAssetAttrToCompanyA { get; set; }
        public Nullable<double> C_ReturnOnNetAssetAttrToCompanyB { get; set; }
        public Nullable<double> C_ReturnOnNetAssetAttrToCompanyC { get; set; }
        public Nullable<double> C_ReturnOnNetAssetAttrToCompanyTTM { get; set; }
        public Nullable<double> ReturnOnTotalAssetAttrToCompanyA { get; set; }
        public Nullable<double> ReturnOnTotalAssetAttrToCompanyB { get; set; }
        public Nullable<double> ReturnOnTotalAssetAttrToCompanyC { get; set; }
        public Nullable<double> ReturnOnTotalAssetAttrToCompanyTTM { get; set; }
        public Nullable<double> ROI { get; set; }
        public System.Guid UniqueID { get; set; }
        public Nullable<System.DateTime> DateAsOfReporting2 { get; set; }
    }
}
