//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apmservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRD_Co
    {
        public TRD_Co()
        {
            this.STK_MKT_DeriativeTradingIndexDaily = new HashSet<STK_MKT_DeriativeTradingIndexDaily>();
            this.STK_MKT_PortfolioBase = new HashSet<STK_MKT_PortfolioBase>();
            this.STK_MKT_RiskFactorDaily = new HashSet<STK_MKT_RiskFactorDaily>();
            this.STK_MKT_TradeDaily = new HashSet<STK_MKT_TradeDaily>();
        }
    
        public Nullable<double> CoutryId { get; set; }
        public string StockId { get; set; }
        public string StockName { get; set; }
        public string CompanyNameCN { get; set; }
        public string CompanyNameEN { get; set; }
        public string IndustryCodeA { get; set; }
        public string IndustryNameA { get; set; }
        public string IndustryCodeB { get; set; }
        public string IndustryNameB { get; set; }
        public string IndustryCodeC { get; set; }
        public string IndustryNameC { get; set; }
        public string EstDate { get; set; }
        public string IPODate { get; set; }
        public string EarliestTradingRecordDate { get; set; }
        public string TradingCurrency { get; set; }
        public Nullable<double> StockIssuePricePremium { get; set; }
        public Nullable<double> StockIssuePrice { get; set; }
        public string StockIssueCurrency { get; set; }
        public Nullable<double> StockIsseQuantity { get; set; }
        public string StockParCurrency { get; set; }
        public string StockIssueDate { get; set; }
        public Nullable<double> StockParValue { get; set; }
        public Nullable<double> ZoneCode { get; set; }
        public string ActivenessCode { get; set; }
        public string ABStockInterchangeCode { get; set; }
        public string StatusChangeDate { get; set; }
        public string HStockInterchangeCode { get; set; }
        public Nullable<double> MarketType { get; set; }
        public string SectorTypeId { get; set; }
    
        public virtual ICollection<STK_MKT_DeriativeTradingIndexDaily> STK_MKT_DeriativeTradingIndexDaily { get; set; }
        public virtual ICollection<STK_MKT_PortfolioBase> STK_MKT_PortfolioBase { get; set; }
        public virtual ICollection<STK_MKT_RiskFactorDaily> STK_MKT_RiskFactorDaily { get; set; }
        public virtual ICollection<STK_MKT_TradeDaily> STK_MKT_TradeDaily { get; set; }
        public virtual TRD_Sector TRD_Sector { get; set; }
    }
}
